#!/bin/sh
#BSUB -J DDPM_Training
#BSUB -o Logs/Training_Logs_%J.out
#BSUB -e Logs/Errors_Logs_%J.err
#BSUB -q gpuv100
#BSUB -gpu "num=1:mode=exclusive_process"
#BSUB -n 16
#BSUB -R "span[hosts=1]"
#BSUB -R "rusage[mem=5G]"
#BSUB -W 8:00
#BSUB -N 
#BSUB 
# end of BSUB options

module load cuda/11.1

source venv3/bin/activate

python Final_Calculation_of_FID.py --sampled_path "MNIST_1" --model_name "MNIST_1_23_11"  --dataset_path "MNIST_all_train_images"




