wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.4
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699892190.8964
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 19
      - 23
      4: 3.8.4
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
epochs:
  desc: null
  value: 500
batch_size:
  desc: null
  value: 12
lr:
  desc: null
  value: 0.0003
